// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PCParts.Data.Context;

#nullable disable

namespace PCParts.Data.Migrations
{
    [DbContext(typeof(PcPartsDbContext))]
    [Migration("20250823081427_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("PCParts.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "CPUs"
                        },
                        new
                        {
                            Id = 2,
                            Name = "GPUs"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Motherboards"
                        },
                        new
                        {
                            Id = 4,
                            Name = "RAM"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Storage"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Power Supplies"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Cases"
                        });
                });

            modelBuilder.Entity("PCParts.Data.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "16-Core 5.4GHz CPU",
                            IsDeleted = false,
                            Name = "Intel Core i7-13700K",
                            Price = 700.00m,
                            Quantity = 15
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "8-Core 5.0GHz CPU with 3D V-Cache",
                            IsDeleted = false,
                            Name = "AMD Ryzen 7 7800X3D",
                            Price = 668.99m,
                            Quantity = 12
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "12GB GDDR6X Graphics Card",
                            IsDeleted = false,
                            Name = "NVIDIA GeForce RTX 4070 Ti",
                            Price = 1616.99m,
                            Quantity = 8
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "20GB GDDR6 Graphics Card",
                            IsDeleted = false,
                            Name = "AMD Radeon RX 7900 XT",
                            Price = 1645.99m,
                            Quantity = 6
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Description = "ATX Motherboard for Intel 13th Gen",
                            IsDeleted = false,
                            Name = "ASUS ROG Strix Z790-E",
                            Price = 379.99m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Description = "AM5 Motherboard for Ryzen 7000",
                            IsDeleted = false,
                            Name = "MSI B650 Tomahawk WiFi",
                            Price = 239.99m,
                            Quantity = 14
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            Description = "2x16GB 6000MHz CL36 RAM Kit",
                            IsDeleted = false,
                            Name = "Corsair Vengeance DDR5 32GB",
                            Price = 169.99m,
                            Quantity = 20
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Description = "2x32GB 6400MHz CL32 RAM Kit",
                            IsDeleted = false,
                            Name = "G.Skill Trident Z5 DDR5 64GB",
                            Price = 349.99m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 5,
                            Description = "Gen 4 NVMe SSD, up to 7450 MB/s",
                            IsDeleted = false,
                            Name = "Samsung 990 Pro 2TB NVMe",
                            Price = 229.99m,
                            Quantity = 18
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            Description = "Gen 4 NVMe SSD, up to 7300 MB/s",
                            IsDeleted = false,
                            Name = "WD Black SN850X 1TB",
                            Price = 129.99m,
                            Quantity = 22
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 6,
                            Description = "850W 80+ Gold Fully Modular PSU",
                            IsDeleted = false,
                            Name = "Corsair RM850x",
                            Price = 149.99m,
                            Quantity = 16
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 6,
                            Description = "1000W 80+ Titanium Fully Modular PSU",
                            IsDeleted = false,
                            Name = "Seasonic Prime TX-1000",
                            Price = 289.99m,
                            Quantity = 7
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 7,
                            Description = "ATX Mid Tower Case with Tempered Glass",
                            IsDeleted = false,
                            Name = "Lian Li PC-O11 Dynamic",
                            Price = 139.99m,
                            Quantity = 9
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 7,
                            Description = "ATX Mid Tower Case with High Airflow",
                            IsDeleted = false,
                            Name = "Fractal Design Meshify 2",
                            Price = 169.99m,
                            Quantity = 11
                        });
                });

            modelBuilder.Entity("PCParts.Data.Models.ProductSale", b =>
                {
                    b.Property<int>("SaleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPriceAtSale")
                        .HasColumnType("TEXT");

                    b.HasKey("SaleId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductSales");
                });

            modelBuilder.Entity("PCParts.Data.Models.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("PCParts.Data.Models.Product", b =>
                {
                    b.HasOne("PCParts.Data.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PCParts.Data.Models.ProductSale", b =>
                {
                    b.HasOne("PCParts.Data.Models.Product", "Product")
                        .WithMany("ProductSales")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PCParts.Data.Models.Sale", "Sale")
                        .WithMany("ProductSales")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("PCParts.Data.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("PCParts.Data.Models.Product", b =>
                {
                    b.Navigation("ProductSales");
                });

            modelBuilder.Entity("PCParts.Data.Models.Sale", b =>
                {
                    b.Navigation("ProductSales");
                });
#pragma warning restore 612, 618
        }
    }
}
